hotfix(dao) ensure 'init()' errors are prefixed with DB name
This fixes a regression introduced in #3310.

If the database is unreachabel when Kong start, it is our policy that
the error message be prefixed with `[postgres error]` (in the case of
PostgreSQL) to help the user troubleshoot the issue.

Prior to this patch, this behavior was changed in #3310, since it
introduced a call to `init()` in the CLI. Users would see:
```
$ kong start
Error: connection refused
```

Instead of:
```
$ kong start
Error: [postgres error] could not retrieve server_version: connection refused
```

From #3411